using AutoMapper;
using CIN.Domain.Payroll.Management;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Application.Payroll.Management.Dtos
{
    [AutoMap(typeof(TblPRLTrnPayrollPackage))]
    public class TblPRLTrnPayrollPackageDto : AutoGeneratedIdKeyAuditableEntityDto<int>
    {
        [Required]
        [StringLength(20)]
        public string PackageCode { get; set; }
        [Required]
        [StringLength(100)]
        public string PackageNameEn { get; set; }
        [StringLength(100)]
        public string PackageNameAr { get; set; }
        //Grade
        [StringLength(20)]
        public string GradeCode { get; set; }
        [StringLength(100)]
        public string GradeName { get; set; }
        //Position
        [StringLength(20)]
        public string PositionCode { get; set; }
        [StringLength(100)]
        public string PositionName { get; set; }
        [StringLength(100)]
        public string PackageName { get; set; }
        [Required]
        public decimal BasicSalary { get; set; }
        public List<TblPRLTrnPayrollPackageComponentDto> PackageComponents { get; set; }
    }
}
