using AutoMapper;
using CIN.Domain.HumanResource.Setup;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Application.HumanResource.SetUp.HRMSetUpDtos
{
    [AutoMap(typeof(TblHRMSysEmployeeStatus))]
    public class TblHRMSysEmployeeStatusDto : AutoGeneratedIdKeyAuditableEntityDto<int>
    {
        [Required]
        [StringLength(20)]
        public string EmployeeStatusCode { get; set; }
        [Required]
        [StringLength(100)]
        public string EmployeeStatusNameEn { get; set; }
        [StringLength(100)]
        public string EmployeeStatusNameAr { get; set; }
    }
}
