using AutoMapper;
using CIN.Domain.HumanResource.Setup;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Application.HumanResource.SetUp.HRMSetUpDtos
{
    [AutoMap(typeof(TblHRMSysGrade))]
    public class TblHRMSysGradeDto : AutoGeneratedIdKeyAuditableEntityDto<int>
    {
        [StringLength(20)]
        [Key]
        public string GradeCode { get; set; }
        [Required]
        [StringLength(100)]
        public string GradeNameEn { get; set; }
        [StringLength(100)]
        public string GradeNameAr { get; set; }
    }
}
