using AutoMapper;
using CIN.Domain;
using CIN.Domain.HumanResource.Setup;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Application.HumanResource.SetUp.HRMSetUpDtos
{
    [AutoMap(typeof(TblHRMSysDependentType))]
    public class TblHRMSysDependentTypeDto : AutoGeneratedIdKeyAuditableEntityDto<int>
    {
        [Required]
        [StringLength(20)]
        public string DependentTypeCode { get; set; }
        [Required]
        [StringLength(100)]
        public string DependentTypeNameEn { get; set; }
        [StringLength(100)]
        public string DependentTypeNameAr { get; set; }
    }
}
