using AutoMapper;
using CIN.Domain.HumanResource.Setup;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Application.HumanResource.SetUp.HRMSetUpDtos
{
    [AutoMap(typeof(TblHRMSysShift))]
    public class TblHRMSysShiftDto : AutoGeneratedIdKeyAuditableEntityDto<int>
    {
        [StringLength(20)]
        [Required]
        public string ShiftCode { get; set; }
        [Required]
        [StringLength(100)]
        public string ShiftNameEn { get; set; }
        [StringLength(100)]
        public string ShiftNameAr { get; set; }
        [Required]
        
        public string InTime { get; set; }
        [Required]
       
        public string OutTime { get; set; }
       
        public string BreakTime { get; set; }
     
        public string InGrace { get; set; }
      
        public string OutGrace { get; set; }
   
        public string WorkingTime { get; set; }
        
        public string NetWorkingTime { get; set; }


       
    }


}
