using AutoMapper;
using CIN.Domain.HumanResource.Setup;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Application.HumanResource.SetUp.HRMSetUpDtos
{
    [AutoMap(typeof(TblHRMSysTitle))]
    public class TblHRMSysTitleDto : AutoGeneratedIdKeyAuditableEntityDto<int>
    {
        [StringLength(20)]
        [Required]
        public string TitleCode { get; set; }
        [Required]
        [StringLength(100)]
        public string TitleNameEn { get; set; }
        [Required]
        [StringLength(100)]
        public string TitleNameAr { get; set; }
    }
}
