using AutoMapper;
using CIN.Domain.HumanResource.Setup;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Application.HumanResource.SetUp.HRMSetUpDtos
{
    [AutoMap(typeof(TblHRMSysBank))]
    public class TblHRMSysBankDto : AutoGeneratedIdKeyAuditableEntityDto<int>
    {
        [StringLength(20)]
        [Required]
        public string BankCode { get; set; }
        [Required]
        [StringLength(100)]
        public string BankNameEn { get; set; }
        [Required]
        [StringLength(100)]
        public string BankNameAr { get; set; }
    }
}
