using AutoMapper;
using CIN.Domain.HumanResource.Setup;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Application.HumanResource.SetUp.HRMSetUpDtos
{
    [AutoMap(typeof(TblHRMSysGender))]
    public class TblHRMSysGenderDto : AutoGeneratedIdKeyAuditableEntityDto<int>
    {
        [StringLength(20)]
        [Required]
        public string GenderCode { get; set; }
        [Required]
        [StringLength(100)]
        public string GenderNameEn { get; set; }
        [StringLength(100)]
        public string GenderNameAr { get; set; }
    }
}
