using AutoMapper;
using CIN.Domain;
using CIN.Domain.HumanResource.Setup;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Application.HumanResource.SetUp.HRMSetUpDtos
{
    [AutoMap(typeof(TblHRMSysGroup))]
    public class TblHRMSysGroupDto : AutoGeneratedIdKeyAuditableEntityDto<int>
    {
        [StringLength(20)]
        [Required]
        public string GroupCode { get; set; }
        [Required]
        [StringLength(20)]
        public string ReligionCode { get; set; }
        [Required]
        [StringLength(100)]
        public string GroupNameEn { get; set; }
        [StringLength(100)]
        public string GroupNameAr { get; set; }
        [StringLength(100)]
        public string ReligionName { get; set; }
    }
}
