using AutoMapper;
using CIN.Domain.HumanResource.Setup;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Application.HumanResource.SetUp.HRMSetUpDtos
{
    [AutoMap(typeof(TblHRMSysInsuranceProvider))]
    public class TblHRMSysInsuranceProviderDto : AutoGeneratedIdKeyAuditableEntityDto<int>
    {
        [Required]
        [StringLength(20)]
        public string InsuranceProviderCode { get; set; }
        [Required]
        [StringLength(100)]
        public string InsuranceProviderNameEn { get; set; }
        [Required]
        [StringLength(100)]
        public string InsuranceProviderNameAr { get; set; }
    }
}
