using AutoMapper;
using CIN.Domain.HumanResource.Setup;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Application.HumanResource.SetUp.HRMSetUpDtos
{
    [AutoMap(typeof(TblHRMSysHoliday))]
    public class TblHRMSysHolidayDto : AutoGeneratedIdKeyAuditableEntityDto<int>
    {
        [Required]
        [StringLength(20)]
        public string HolidayCode { get; set; }
        [Required]
        [StringLength(100)]
        public string HolidayNameEn { get; set; }
        [StringLength(100)]
        public string HolidayNameAr { get; set; }
        //Date
        [Required]
        [Column(TypeName = "date")]
        public DateTime Date { get; set; }
        public bool Checked { get; set; }
    }
}
