using AutoMapper;
using CIN.Domain.HumanResource.Setup;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Application.HumanResource.SetUp.HRMSetUpDtos
{
    [AutoMap(typeof(TblHRMSysCourseType))]
    public class TblHRMSysCourseTypeDto : AutoGeneratedIdKeyAuditableEntityDto<int>
    {
        [StringLength(20)]
        [Required]
        public string CourseTypeCode { get; set; }
        [Required]
        [StringLength(100)]
        public string CourseTypeNameEn { get; set; }
        [Required]
        [StringLength(100)]
        public string CourseTypeNameAr { get; set; }
    }
}
