using AutoMapper;
using CIN.Domain.HumanResource.Setup;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Application.HumanResource.SetUp.HRMSetUpDtos
{
    [AutoMap(typeof(TblHRMSysDocumentType))]
    public class TblHRMSysDocumentTypeDto : AutoGeneratedIdKeyAuditableEntityDto<int>
    {
        [StringLength(20)]
        [Required]
        public string DocumentTypeCode { get; set; }
        [Required]
        [StringLength(100)]
        public string DocumentTypeNameEn { get; set; }
        [StringLength(100)]
        public string DocumentTypeNameAr { get; set; }
        [Required]
        public bool IsMandatory { get; set; }
    }
}
