using AutoMapper;
using CIN.Domain.HumanResource.Setup;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Application.HumanResource.SetUp.HRMSetUpDtos
{
    [AutoMap(typeof(TblHRMSysHolidayCalendar))]
    public class TblHRMSysHolidayCalendarDto : AutoGeneratedIdKeyAuditableEntityDto<int>
    {
        [Required]
        [StringLength(20)]
        public string HolidayCalendarCode { get; set; }
        [Required]
        public int Year { get; set; }
        [Required]
        [StringLength(100)]
        public string HolidayCalendarNameEn { get; set; }
        [StringLength(100)]
        public string HolidayCalendarNameAr { get; set; }
        [StringLength(500)]
        public string Remarks { get; set; }

        public List<TblHRMSysHolidayCalendarMappingDto> HolidayCalendarMappings { get; set; }
    }
}