using AutoMapper;
using CIN.Domain.HumanResource.Setup;
using System.ComponentModel.DataAnnotations;

namespace CIN.Application.HumanResource.SetUp.HRMSetUpDtos
{

    [AutoMap(typeof(TblHRMSysLeaveType))]
    public class TblHRMSysLeaveTypeDto : AutoGeneratedIdKeyAuditableEntityDto<int>
    {
        [StringLength(20)]
        public string LeaveTypeCode { get; set; }
        [StringLength(256)]
        public string LeaveTypeEn { get; set; }
        [StringLength(256)]
        public string LeaveTypeAr { get; set; }

        public bool IsReduceFromVacation { get; set; }

        public bool IsSalaryPaid { get; set; }

        public bool IsDocumentRequired { get; set; }

        public bool IsLocalColumnRequired { get; set; }

        public int MaxLeaveDays { get; set; }

        public bool IsFinanceApprovalRequired { get; set; }
        [StringLength(256)]
        public string LeaveCode { get; set; }

        public int Type { get; set; }

        public decimal SalaryPercentage { get; set; }
        [StringLength(20)]
        public string Gender { get; set; }
        [StringLength(50)]
        public string NationalityId { get; set; }

        public bool IsCarryForward { get; set; }

        public bool IsTravelRequired { get; set; }

        public bool IsExitAndreEntryRequired { get; set; }
        public bool IsUsedForVacation { get; set; }

        public decimal MaxAccumulatedLeave { get; set; }

        public decimal MonthlyProRataLeaves { get; set; }
        public bool IsLeaveEncashment { get; set; }

    }

    public class VacationRequestLeaveTypeDto
    {
        public string Text { get; set; }
        public string Value { get; set; }
        public decimal Assigned { get; set; } = 0; //Total Default Leaves
        public decimal Availed { get; set; } = 0;
    }
}

