using AutoMapper;
using CIN.Domain.HumanResource.Setup;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Application.HumanResource.SetUp.HRMSetUpDtos
{
    [AutoMap(typeof(TblHRMSysLanguage))]
    public class TblHRMSysLanguageDto : AutoGeneratedIdKeyAuditableEntityDto<int>
    {
        [Required]
        [StringLength(20)]
        public string LanguageCode { get; set; }
        [Required]
        [StringLength(100)]
        public string LanguageNameEn { get; set; }
        [Required]
        [StringLength(100)]
        public string LanguageNameAr { get; set; }
    }
}
