using AutoMapper;
using CIN.Domain.HumanResource.Setup;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Application.HumanResource.SetUp.HRMSetUpDtos
{
    [AutoMap(typeof(TblHRMSysNationality))]
    public class TblHRMSysNationalityDto : AutoGeneratedIdKeyAuditableEntityDto<int>
    {
        [Required]
        [StringLength(20)]
        public string NationalityCode { get; set; }
        [Required]
        [StringLength(100)]
        public string NationalityNameEn { get; set; }
        [Required]
        [StringLength(100)]
        public string NationalityNameAr { get; set; }
        public bool IsDelete { get; set; }
    }
}
