using AutoMapper;
using CIN.Domain.HumanResource.Setup;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Application.HumanResource.SetUp.HRMSetUpDtos
{
    [AutoMap(typeof(TblHRMSysAddressType))]
    public class TblHRMSysAddressTypeDto : AutoGeneratedIdKeyAuditableEntityDto<int>
    {
        [Required]
        [StringLength(20)]
        public string AddressTypeCode { get; set; }
        [Required]
        [StringLength(100)]
        public string AddressTypeNameEn { get; set; }
        [Required]
        [StringLength(100)]
        public string AddressTypeNameAr { get; set; }
        public bool IsDelete { get; set; }
    }
}
