using AutoMapper;
using CIN.Domain.HumanResource.Setup;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Application.HumanResource.SetUp.HRMSetUpDtos
{
    [AutoMap(typeof(TblHRMSysEmployeeType))]
    public class TblHRMSysEmployeeTypeDto : AutoGeneratedIdKeyAuditableEntityDto<int>
    {
        [Required]
        [StringLength(20)]
        public string EmployeeTypeCode { get; set; }
        [Required]
        [StringLength(100)]
        public string EmployeeTypeNameEn { get; set; }
        [Required]
        [StringLength(100)]
        public string EmployeeTypeNameAr { get; set; }
    }
}
