using AutoMapper;
using CIN.Domain.HumanResource.Setup;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Application.HumanResource.SetUp.HRMSetUpDtos
{
    [AutoMap(typeof(TblHRMSysBloodGroup))]
    public class TblHRMSysBloodGroupDto : AutoGeneratedIdKeyAuditableEntityDto<int>
    {
        [Required]
        [StringLength(20)]
        public string BloodGroupCode { get; set; }
        [Required]
        [StringLength(100)]
        public string BloodGroupNameEn { get; set; }
        [StringLength(100)]
        public string BloodGroupNameAr { get; set; }
    }
}
