using AutoMapper;
using CIN.Domain.HumanResource.Setup;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Application.HumanResource.SetUp.HRMSetUpDtos
{
    [AutoMap(typeof(TblHRMSysBankBranch))]
    public class TblHRMSysBankBranchDto : AutoGeneratedIdKeyAuditableEntityDto<int>
    {
        //IFSC Code
        [Required]
        [StringLength(20)]
        public string IFSCCode { get; set; }

        //Bank Code
        [Required]
        [StringLength(20)]
        public string BankCode { get; set; }

        //Branch Name
        [StringLength(100)]
        public string BranchNameEn { get; set; }

        //Branch Name in Arabic
        [StringLength(100)]
        public string BranchNameAr { get; set; }
        //Branch Name
        [StringLength(100)]
        public string BankNameEn { get; set; }

        //Branch Name in Arabic
        [StringLength(100)]
        public string BankNameAr { get; set; }
    }
}
