using AutoMapper;
using CIN.Domain.HumanResource.Setup;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Application.HumanResource.SetUp.HRMSetUpDtos
{
    [AutoMap(typeof(TblHRMSysMaritalStatus))]
    public class TblHRMSysMaritalStatusDto : AutoGeneratedIdKeyAuditableEntityDto<int>
    {
        [StringLength(20)]
        [Required]
        public string MaritalStatusCode { get; set; }
        [Required]
        [StringLength(100)]
        public string MaritalStatusNameEn { get; set; }
        [StringLength(100)]
        public string MaritalStatusNameAr { get; set; }
    }
}
