using AutoMapper;
using CIN.Domain.HumanResource.Setup;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CIN.Application.HumanResource.SetUp.HRMSetUpDtos
{
    [AutoMap(typeof(TblHRMSysLeaveTemplate))]
    public class TblHRMSysLeaveTemplateDto : AutoGeneratedIdKeyAuditableEntityDto<int>
    {
        [StringLength(20)]
        public string TemplateCode { get; set; }
        [Required]
        [StringLength(100)]
        public string TemplateNameEn { get; set; }
        [StringLength(100)]
        public string TemplateNameAr { get; set; }
        [StringLength(20)]
        public string GradeCode { get; set; }
        [StringLength(20)]
        public string PositionCode { get; set; }

        [StringLength(500)]
        public string Remarks { get; set; }
        public List<TblHRMSysLeaveTemplateMappingDto> LeaveTypeCodes { get; set; }
    }

    public class TblHRMSysLeaveTemplateMappingDto
    {
        [StringLength(20)]
        public string LeaveTypeCode { get; set; }
        public string LeaveTypeName { get; set; }
        public decimal Count { get; set; }
        public bool IsChecked { get; set; }
        public bool CanSubmit { get; set; }
    }
}
