using AutoMapper;
using CIN.Domain.HumanResource.Setup;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Application.HumanResource.SetUp.HRMSetUpDtos
{
    [AutoMap(typeof(TblHRMSysVisaType))]
    public class TblHRMSysVisaTypeDto : AutoGeneratedIdKeyAuditableEntityDto<int>
    {
        [StringLength(20)]
        public string VisaTypeCode { get; set; }
        [Required]
        [StringLength(100)]
        public string VisaTypeNameEn { get; set; }
        [StringLength(100)]
        public string VisaTypeNameAr { get; set; }
        //Country
        [Required]
        [StringLength(50)]
        public string CountryCode { get; set; }
        [StringLength(100)]
        public string CountryName { get; set; }
    }
}
