using CIN.Domain.HumanResource.Setup;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Domain.Payroll.Management
{
    [Table("tblPRLTrnPayrollPackage")]
    public class TblPRLTrnPayrollPackage : AutoGeneratedIdKeyAuditableEntity<int>
    {
        [Key]
        [StringLength(20)]
        public string PackageCode { get; set; }
        [Required]
        [StringLength(100)]
        public string PackageNameEn { get; set; }
        [StringLength(100)]
        public string PackageNameAr { get; set; }

        //Grade
        [ForeignKey(nameof(GradeCode))]
        public TblHRMSysGrade SysGrade { get; set; }
        [StringLength(20)]
        public string GradeCode { get; set; }

        //Position
        [ForeignKey(nameof(PositionCode))]
        public TblHRMSysPosition SysPosition { get; set; }
        [StringLength(20)]
        public string PositionCode { get; set; }
    }
}
