using AutoMapper;
using CIN.Domain.Payroll.Setup;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Application.Payroll.SetUp.Dtos
{
    [AutoMap(typeof(TblPRLSysPayrollPeriod))]
    public class TblPRLSysPayrollPeriodDto : AutoGeneratedIdKeyAuditableEntityDto<int>
    {
        [Required]
        [StringLength(20)]
        public string PayrollPeriodCode { get; set; }
        [Required]
        [StringLength(100)]
        public string PayrollPeriodNameEn { get; set; }
        [StringLength(100)]
        public string PayrollPeriodNameAr { get; set; }
        [Required]
        [Column(TypeName = "date")]
        public DateTime PayrollPeriodStartDate { get; set; }
        [Required]
        [Column(TypeName = "date")]
        public DateTime PayrollPeriodEndDate { get; set; }
        public bool IsOpen { get; set; }
        public bool IsClose { get; set; }
    }
}
