using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Domain.HumanResource.ServiceRequest
{
    [Table("tblHRMSysServiceRequestType")]
    public class TblHRMSysServiceRequestType : AutoGeneratedIdKeyAuditableEntity<int>
    {
        [StringLength(20)]
        [Key]
        public string ServiceRequestTypeCode { get; set; }
        [Required]
        [StringLength(100)]
        public string ServiceRequestTypeNameEn { get; set; }
        [StringLength(100)]
        public string ServiceRequestTypeNameAr { get; set; }
        [StringLength(100)]
        public string Icon { get; set; }
    }
}
