using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Domain.HumanResource.Setup
{
    [Table("tblHRMSysDivision")]
    public class TblHRMSysDivision : AutoGeneratedIdKeyAuditableEntity<int>
    {
        [Key]
        [StringLength(20)]
        public string DivisionCode { get; set; }
        [Required]
        [StringLength(100)]
        public string DivisionNameEn { get; set; }
        [StringLength(100)]
        public string DivisionNameAr { get; set; }
    }
}
