using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Domain.HumanResource.Setup
{
    [Table("tblHRMSysFlightClass")]
    public class TblHRMSysFlightClass : AutoGeneratedIdKeyAuditableEntity<int>
    {
        [StringLength(20)]
        [Key]
        public string FlightClassCode { get; set; }
        [Required]
        [StringLength(100)]
        public string FlightClassNameEn { get; set; }
        [StringLength(100)]
        public string FlightClassNameAr { get; set; }
    }
}
