using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Domain.HumanResource.Setup
{
    [Table("tblHRMSysDepartment")]
    public class TblHRMSysDepartment : AutoGeneratedIdKeyAuditableEntity<int>
    {
        [Key]
        [StringLength(20)]
        public string DepartmentCode { get; set; }
        [Required]
        [StringLength(100)]
        public string DepartmentNameEn { get; set; }
        [StringLength(100)]
        public string DepartmentNameAr { get; set; }
        [ForeignKey(nameof(DivisionCode))]
        public TblHRMSysDivision SysDivision { get; set; }
        [Required]
        [StringLength(20)]
        public string DivisionCode { get; set; }
    }
}
