using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Domain.HumanResource.Setup
{
    [Table("tblHRMSysLeaveTemplate")]
    public class TblHRMSysLeaveTemplate : AutoGeneratedIdKeyAuditableEntity<int>
    {
        [Key]
        [StringLength(20)]
        public string TemplateCode { get; set; }
        [Required]
        [StringLength(100)]
        public string TemplateNameEn { get; set; }
        [StringLength(100)]
        public string TemplateNameAr { get; set; }
        [StringLength(20)]
        public string GradeCode { get; set; }
        [StringLength(20)]
        public string PositionCode { get; set; }

        [StringLength(500)]
        public string Remarks { get; set; }
    }
}
