using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Domain.HumanResource.Setup
{
    [Table("tblHRMSysBankBranch")]
    public class TblHRMSysBankBranch : AutoGeneratedIdKeyAuditableEntity<int>
    {
        //IFSC Code
        [StringLength(20)]
        [Key]
        public string IFSCCode { get; set; }

        //Bank Code
        [ForeignKey(nameof(BankCode))]
        public TblHRMSysBank SysBank { get; set; }
        [Required]
        [StringLength(20)]
        public string BankCode { get; set; }

        //Branch Name
        [StringLength(100)]
        public string BranchNameEn { get; set; }

        //Branch Name in Arabic
        [StringLength(100)]
        public string BranchNameAr { get; set; }
    }
}
