using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Domain.HumanResource.Setup
{
    [Table("tblHRMSysHoliday")]
    public class TblHRMSysHoliday : AutoGeneratedIdKeyAuditableEntity<int>
    {
        [Key]
        [StringLength(20)]
        public string HolidayCode { get; set; }
        [Required]
        [StringLength(100)]
        public string HolidayNameEn { get; set; }
        [StringLength(100)]
        public string HolidayNameAr { get; set; }
        //Date
        [Required]
        [Column(TypeName = "date")]
        public DateTime Date { get; set; }
    }
}
