using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Domain.HumanResource.Setup
{
    [Table("tblHRMSysAddressType")]
    public class TblHRMSysAddressType : AutoGeneratedIdKeyAuditableEntity<int>
    {
        [StringLength(20)]
        [Key]
        public string AddressTypeCode { get; set; }
        [Required]
        [StringLength(100)]
        public string AddressTypeNameEn { get; set; }
        [StringLength(100)]
        public string AddressTypeNameAr { get; set; }
    }
}
