using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Domain.HumanResource.Setup
{
    [Table("tblHRMSysQualification")]
    public class TblHRMSysQualification : AutoGeneratedIdKeyAuditableEntity<int>
    {
        [StringLength(20)]
        [Key]
        public string QualificationCode { get; set; }
        [Required]
        [StringLength(100)]
        public string QualificationNameEn { get; set; }
        [StringLength(100)]
        public string QualificationNameAr { get; set; }
        [Required]
        public bool IsTechnicalQualification { get; set; }        
        //Degree Type
        [ForeignKey(nameof(DegreeTypeCode))]
        public TblHRMSysDegreeType SysDegreeType { get; set; }
        [StringLength(20)]
        [Required]
        public string DegreeTypeCode { get; set; }
    }
}
