using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Domain.HumanResource.Setup
{
    [Table("tblHRMSysGrade")]
    public class TblHRMSysGrade : AutoGeneratedIdKeyAuditableEntity<int>
    {
        [StringLength(20)]
        [Key]
        public string GradeCode { get; set; }
        [Required]
        [StringLength(100)]
        public string GradeNameEn { get; set; }
        [Required]
        [StringLength(100)]
        public string GradeNameAr { get; set; }
    }
}
