using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Domain.HumanResource.Setup
{
    [Table("tblHRMSysShift")]
    public class TblHRMSysShift : AutoGeneratedIdKeyAuditableEntity<int>
    {
        [StringLength(20)]
        [Key]
        public string ShiftCode { get; set; }
        [Required]
        [StringLength(100)]
        public string ShiftNameEn { get; set; }
        [StringLength(100)]
        public string ShiftNameAr { get; set; }
        [Required]
        public TimeSpan InTime { get; set; }
        [Required]
        public TimeSpan OutTime { get; set; }
        public TimeSpan BreakTime { get; set; }
        public TimeSpan InGrace { get; set; }
        public TimeSpan OutGrace { get; set; }
        public TimeSpan WorkingTime { get; set; }
        public TimeSpan NetWorkingTime { get; set; }
    }
}
