using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Domain.HumanResource.Setup
{
    [Table("tblHRMSysGender")]
    public class TblHRMSysGender : AutoGeneratedIdKeyAuditableEntity<int>
    {
        [StringLength(20)]
        [Key]
        public string GenderCode { get; set; }
        [Required]
        [StringLength(100)]
        public string GenderNameEn { get; set; }
        [Required]
        [StringLength(100)]
        public string GenderNameAr { get; set; }
    }
}
