using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Domain.HumanResource.Setup
{
    [Table("tblHRMSysDegreeType")]
    public class TblHRMSysDegreeType : AutoGeneratedIdKeyAuditableEntity<int>
    {
        [StringLength(20)]
        [Key]
        public string DegreeTypeCode { get; set; }
        [Required]
        [StringLength(100)]
        public string DegreeTypeNameEn { get; set; }
        [StringLength(100)]
        public string DegreeTypeNameAr { get; set; }
    }
}
