using CIN.Domain.SystemSetup;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Domain.HumanResource.Setup
{
    [Table("tblHRMSysVisaType")]
    public class TblHRMSysVisaType : AutoGeneratedIdKeyAuditableEntity<int>
    {
        [StringLength(20)]
        [Key]
        public string VisaTypeCode { get; set; }
        [Required]
        [StringLength(100)]
        public string VisaTypeNameEn { get; set; }
        [Required]
        [StringLength(100)]
        public string VisaTypeNameAr { get; set; }
        //Country
        [ForeignKey(nameof(CountryCode))]
        public TblErpSysCountryCode SysCountryCode { get; set; }
        [Required]
        [StringLength(50)]
        public string CountryCode { get; set; }
    }
}
