using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CIN.Domain.HumanResource.Setup
{
    [Table("tblHRMSysLeaveType")]
    public class TblHRMSysLeaveType : AutoGeneratedIdKeyAuditableEntity<int>
    {
        [StringLength(20)]
        [Key]
        public string LeaveTypeCode { get; set; }
        [StringLength(256)]
        public string LeaveTypeEn { get; set; }
        [StringLength(256)]
        public string LeaveTypeAr { get; set; }

        public bool IsReduceFromVacation { get; set; }

        public bool IsSalaryPaid { get; set; }

        public bool IsDocumentRequired { get; set; }

        public bool IsLocalColumnRequired { get; set; }

        public int MaxLeaveDays { get; set; }

        public bool IsFinanceApprovalRequired { get; set; }
        [StringLength(256)]
        public string LeaveCode { get; set; }

        public int Type { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal SalaryPercentage { get; set; }
        [StringLength(20)]
        public string Gender { get; set; }

        [StringLength(50)]
        public string NationalityId { get; set; }

        public bool IsCarryForward { get; set; }

        public bool IsTravelRequired { get; set; }

        public bool IsExitAndreEntryRequired { get; set; }
        public bool IsUsedForVacation { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal MaxAccumulatedLeave { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal MonthlyProRataLeaves { get; set; }
        public bool IsLeaveEncashment { get; set; }

    }

}
