using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Domain.HumanResource.Setup
{
    [Table("tblHRMSysBank")]
    public class TblHRMSysBank : AutoGeneratedIdKeyAuditableEntity<int>
    {
        [StringLength(20)]
        [Key]
        public string BankCode { get; set; }
        [Required]
        [StringLength(100)]
        public string BankNameEn { get; set; }
        [Required]
        [StringLength(100)]
        public string BankNameAr { get; set; }
    }
}
