using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Domain.HumanResource.Setup
{
    [Table("tblHRMSysVacationPolicy")]
    public class TblHRMSysVacationPolicy : AutoGeneratedIdKeyAuditableEntity<int>
    {
        [Key]
        [StringLength(20)]
        public string VacationPolicyCode { get; set; }

        [Required]
        [StringLength(100)]
        public string VacationPolicyNameEn { get; set; }

        [StringLength(100)]
        public string VacationPolicyNameAr { get; set; }

        //Grade
        [ForeignKey(nameof(GradeCode))]
        public TblHRMSysGrade SysGrade { get; set; }
        [StringLength(20)]
        public string GradeCode { get; set; }

        //Position
        [ForeignKey(nameof(PositionCode))]
        public TblHRMSysPosition SysPosition { get; set; }
        [StringLength(20)]
        public string PositionCode { get; set; }

        [Required]
        public int AnnualVacationDays { get; set; }

        //Max. No. of days allowed in the vacation duration
        [Required]
        public int MaximumDaysAllowed { get; set; }

        //For Eg: 30 Vacation Days are available in every 12 Months.
        [Required]
        public int VacationDurationInMonths { get; set; }

        //Allow Air Ticket
        public bool IsAirTicketAllowed { get; set; }

        //Air Ticket Schedule Duration in months. For Eg: 1 Air Ticket is available in every 12 Months.
        public int AirTicketDurationInMonths { get; set; }

        //Allow Family Ticket along with the Employee
        public bool IsFamilyTicketAllowed { get; set; }

        //Family Air Ticket Schedule Duration. For Eg: 1 Family Air Ticket is available in every 12 Months.
        public int FamilyAirTicketDuration { get; set; }

        //Require Exit Re-Entry on Travel
        public bool IsExitReEntryRequired { get; set; }

        //Allow Advance Vacation Pay 
        public bool IsAdvanceVacationPayAllowed { get; set; }

        //Allow employee to extend vacation
        public bool IsVacationExtensionAllowed { get; set; }
    }
}
