using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Domain.HumanResource.Setup
{
    [Table("tblHRMSysLanguage")]
    public class TblHRMSysLanguage : AutoGeneratedIdKeyAuditableEntity<int>
    {
        [StringLength(20)]
        [Key]
        public string LanguageCode { get; set; }
        [Required]
        [StringLength(100)]
        public string LanguageNameEn { get; set; }
        [Required]
        [StringLength(100)]
        public string LanguageNameAr { get; set; }
    }
}
