using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Domain.HumanResource.Setup
{
    [Table("tblHRMSysEmployeeStatus")]
    public class TblHRMSysEmployeeStatus : AutoGeneratedIdKeyAuditableEntity<int>
    {
        [Key]
        [StringLength(20)]
        public string EmployeeStatusCode { get; set; }
        [Required]
        [StringLength(100)]
        public string EmployeeStatusNameEn { get; set; }
        [StringLength(100)]
        public string EmployeeStatusNameAr { get; set; }
    }
}
