using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Domain.HumanResource.Setup
{
    [Table("tblHRMSysGroup")]
    public class TblHRMSysGroup : AutoGeneratedIdKeyAuditableEntity<int>
    {
        [StringLength(20)]
        [Key]
        public string GroupCode { get; set; }
        //Religion Code
        [ForeignKey(nameof(ReligionCode))]
        public TblHRMSysReligion SysReligion { get; set; }
        [Required]
        [StringLength(20)]
        public string ReligionCode { get; set; }
        [Required]
        [StringLength(100)]
        public string GroupNameEn { get; set; }
        [Required]
        [StringLength(100)]
        public string GroupNameAr { get; set; }

    }
}
