using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Domain.HumanResource.Setup
{
    [Table("tblHRMSysDependentType")]
    public class TblHRMSysDependentType: AutoGeneratedIdKeyAuditableEntity<int>
    {
        [StringLength(20)]
        [Key]
        public string DependentTypeCode { get; set; }
        [Required]
        [StringLength(100)]
        public string DependentTypeNameEn { get; set; }
        [Required]
        [StringLength(100)]
        public string DependentTypeNameAr { get; set; }
    }
}
