using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Domain.HumanResource.Setup
{
    [Table("tblHRMSysReligion")]
    public class TblHRMSysReligion : AutoGeneratedIdKeyAuditableEntity<int>
    {
        [StringLength(20)]
        [Key]
        public string ReligionCode { get; set; }
        [Required]
        [StringLength(100)]
        public string ReligionNameEn { get; set; }
        [Required]
        [StringLength(100)]
        public string ReligionNameAr { get; set; }
    }
}
