using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Domain.HumanResource.Setup
{
    [Table("tblHRMSysSubGroup")]
    public class TblHRMSysSubGroup : AutoGeneratedIdKeyAuditableEntity<int>
    {
        [StringLength(20)]
        [Key]
        public string SubGroupCode { get; set; }
        [Required]
        [StringLength(100)]
        public string SubGroupNameEn { get; set; }
        [Required]
        [StringLength(100)]
        public string SubGroupNameAr { get; set; }
        [Required]
        [ForeignKey(nameof(GroupCode))]
        public TblHRMSysGroup SysGroupCode { get; set; }
        public string GroupCode { get; set; }
    }
}
