using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Domain.HumanResource.Setup
{
    [Table("tblHRMSysEmployeeType")]
    public class TblHRMSysEmployeeType: AutoGeneratedIdKeyAuditableEntity<int>
    {
        [StringLength(20)]
        [Key]
        public string EmployeeTypeCode { get; set; }
        [Required]
        [StringLength(100)]
        public string EmployeeTypeNameEn { get; set; }
        [Required]
        [StringLength(100)]
        public string EmployeeTypeNameAr { get; set; }
    }
}
