// <auto-generated />
using System;
using CIN.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CIN.DB.One.Migrations.DMC
{
    [DbContext(typeof(DMCContext))]
    [Migration("20221108111805_addAdmissionColumnInStudentMaster")]
    partial class addAdmissionColumnInStudentMaster
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("CIN.Domain.OpeartionsMgt.HRM_DEF_Branch", b =>
                {
                    b.Property<long>("BranchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("BranchCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchName_AR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchName_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("BusinessUnitID")
                        .HasColumnType("bigint");

                    b.Property<long?>("CompanyID")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("IsSystem")
                        .HasColumnType("int");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BranchID");

                    b.ToTable("HRM_DEF_Branch");
                });

            modelBuilder.Entity("CIN.Domain.OpeartionsMgt.HRM_DEF_Department", b =>
                {
                    b.Property<long>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long>("CostCenterID")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentName_AR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentName_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("DivisionID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("IsSystem")
                        .HasColumnType("int");

                    b.Property<long>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("DepartmentID");

                    b.ToTable("HRM_DEF_Department");
                });

            modelBuilder.Entity("CIN.Domain.OpeartionsMgt.HRM_DEF_EmployeeOff", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dow")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<string>("SiteCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("HRM_DEF_EmployeeOff");
                });

            modelBuilder.Entity("CIN.Domain.OpeartionsMgt.HRM_DEF_EmployeeShiftMaster", b =>
                {
                    b.Property<long>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<TimeSpan?>("BreakTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("InGrace")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("InTime")
                        .HasColumnType("time");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsOff")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("NetWorkingTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("OutGrace")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("OutTime")
                        .HasColumnType("time");

                    b.Property<string>("ShiftCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShiftName_AR")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShiftName_EN")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeSpan?>("WorkingTime")
                        .HasColumnType("time");

                    b.HasKey("ShiftId");

                    b.ToTable("HRM_DEF_EmployeeShiftMaster");
                });

            modelBuilder.Entity("CIN.Domain.OpeartionsMgt.HRM_DEF_Project", b =>
                {
                    b.Property<long>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("IsSystem")
                        .HasColumnType("int");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName_AR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ProjectSiteID")
                        .HasColumnType("bigint");

                    b.Property<string>("SiteCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectID");

                    b.ToTable("HRM_DEF_Project");
                });

            modelBuilder.Entity("CIN.Domain.OpeartionsMgt.HRM_DEF_Site", b =>
                {
                    b.Property<long>("SiteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long?>("BranchID")
                        .HasColumnType("bigint");

                    b.Property<string>("CityCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ProjectID")
                        .HasColumnType("bigint");

                    b.Property<string>("SiteCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteName_AR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteName_EN")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SiteID");

                    b.ToTable("HRM_DEF_Site");
                });

            modelBuilder.Entity("CIN.Domain.OpeartionsMgt.HRM_TRAN_Employee", b =>
                {
                    b.Property<long>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmployeeName_AR")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmployeeNumber")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EmployeeID");

                    b.ToTable("HRM_TRAN_Employee");
                });

            modelBuilder.Entity("CIN.Domain.OpeartionsMgt.HRM_TRAN_EmployeePrimarySites_Log", b =>
                {
                    b.Property<long>("EmployeePrimarySitesLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<string>("EmployeeNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SiteCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TransferredDate")
                        .HasColumnType("date");

                    b.HasKey("EmployeePrimarySitesLogID");

                    b.ToTable("HRM_TRAN_EmployeePrimarySites_Log");
                });

            modelBuilder.Entity("CIN.Domain.OpeartionsMgt.HRM_TRAN_EmployeeTimeChart", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<bool?>("ApproveAttn1")
                        .HasColumnType("bit");

                    b.Property<bool?>("ApproveAttn2")
                        .HasColumnType("bit");

                    b.Property<bool?>("ApproveAttn3")
                        .HasColumnType("bit");

                    b.Property<string>("AttnFlag")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("CustomerCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("date");

                    b.Property<long?>("EmployeeID")
                        .HasColumnType("bigint");

                    b.Property<string>("EmployeeNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeSpan?>("EstimatedInTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("EstimatedNetWorkingTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("EstimatedOutTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("InTime")
                        .HasColumnType("time");

                    b.Property<bool?>("IsLate")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPunchedOutNextDay")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsSpecialDay")
                        .HasColumnType("bit");

                    b.Property<long?>("LateHours")
                        .HasColumnType("bigint");

                    b.Property<TimeSpan?>("NWT")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("NetWorkingTime")
                        .HasColumnType("bigint");

                    b.Property<TimeSpan?>("OutTime")
                        .HasColumnType("time");

                    b.Property<long?>("OverTimeHours")
                        .HasColumnType("bigint");

                    b.Property<string>("ProjectCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("ProjectID")
                        .HasColumnType("bigint");

                    b.Property<string>("ShiftCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long?>("ShiftId")
                        .HasColumnType("bigint");

                    b.Property<byte?>("ShiftNumber")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("ShiftTime")
                        .HasColumnType("date");

                    b.Property<string>("SiteCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long?>("SiteID")
                        .HasColumnType("bigint");

                    b.Property<TimeSpan?>("TWT")
                        .HasColumnType("time");

                    b.HasKey("ID");

                    b.ToTable("HRM_TRAN_EmployeeTimeChart");
                });
#pragma warning restore 612, 618
        }
    }
}
