using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Domain.Payroll.Setup
{
    [Table("tblPRLSysPayrollPeriod")]
    public class TblPRLSysPayrollPeriod : AutoGeneratedIdKeyAuditableEntity<int>
    {
        [Key]
        [StringLength(20)]
        public string PayrollPeriodCode { get; set; }
        [Required]
        [StringLength(100)]
        public string PayrollPeriodNameEn { get; set; }
        [StringLength(100)]
        public string PayrollPeriodNameAr { get; set; }
        [Required]
        [Column(TypeName = "date")]
        public DateTime PayrollPeriodStartDate { get; set; }
        [Required]
        [Column(TypeName = "date")]
        public DateTime PayrollPeriodEndDate { get; set; }
        public bool IsOpen { get; set; }
        public bool IsClose { get; set; }
    }
}
