using AutoMapper;
using CIN.Domain.TimeAndAttendance.Setup;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Application.TimeAndAttendance.Setup.TNASetUpDtos
{
    [AutoMap(typeof(TblTNASysPayrollGroup))]
    public class TblTNASysPayrollGroupDto : AutoGeneratedIdKeyAuditableEntityDto<int>
    {
        [StringLength(20)]
        public string PayrollGroupCode { get; set; }
        [Required]
        [StringLength(100)]
        public string PayrollGroupNameEn { get; set; }
        [StringLength(100)]
        public string PayrollGroupNameAr { get; set; }
        [Required]
        [Column(TypeName = "date")]
        public DateTime PayrollGroupStartDate { get; set; }
        [Required]
        [Column(TypeName = "date")]
        public DateTime PayrollGroupEndDate { get; set; }
    }
}
