using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Domain.TimeAndAttendance.Setup
{
    [Table("tblTNASysPayrollGroup")]
    public class TblTNASysPayrollGroup : AutoGeneratedIdKeyAuditableEntity<int>
    {
        [Key]
        [StringLength(20)]
        public string PayrollGroupCode { get; set; }
        [Required]
        [StringLength(100)]
        public string PayrollGroupNameEn { get; set; }
        [StringLength(100)]
        public string PayrollGroupNameAr { get; set; }
        [Required]
        [Column(TypeName = "date")]
        public DateTime PayrollGroupStartDate { get; set; }
        [Required]
        [Column(TypeName = "date")]
        public DateTime PayrollGroupEndDate { get; set; }
    }
}
